### ISSUE TITLE
能不能帮我修改一些功能

### ISSUE THREAD

**Issue by magicdict** [yutuo/editor.md#1]
您好，
由于原作者一直没有更新编辑器，本人的JS水平也不高，能不能请您帮忙修改一些功能。
我现在在开发一个博客网站，里面使用了这个编辑器，但是很多地方都觉得多少有一些BUG，能不能请您帮忙修改一下呢。请问您在什么地方，我在上海。
1.这个编辑器的GetPreViewedHTML必须在Watch模式下才能获得，但是很多时候，用户是关闭Watch模式的，所以拿不到PreviewHTML，由于不知道内部机制，所以不知道有什么简单的方法修改吗。
2.CodeMirror如何能够快速的更新，我看到你的版本里面已经有更新了。
谢谢。

正在开发的网站：
http://www.codesnippet.info
当前的网站的数据只有从博客园采集的标题信息。
其他的数据都是工具模拟的。同时如果你有兴趣，我们可以一些讨论如何开发一个技术博客。

**Comment by yutuo** [comment]
> 1.这个编辑器的GetPreViewedHTML必须在Watch模式下才能获得，但是很多时候，用户是关闭Watch模式的，所以拿不到PreviewHTML，由于不知道内部机制，所以不知道有什么简单的方法修改吗。

这个修改有些麻烦，没有太简单的方法。

> 2.CodeMirror如何能够快速的更新，我看到你的版本里面已经有更新了。

把最新的CodeMirror更新到lib里，然后用gulp编译就能更新。

我现在觉得editor.md有些东西不太好用，正打算自己写一下Markdown的工具。现在还只是完成了一部分，没有实现工具条和快捷键。地址：https://github.com/yutuo/mdeditor.yt

**Comment by magicdict** [comment]
感谢你的回复，
我想问一下，你自己的MD工具，大概什么时候可以完成？是否为持续改进？
现在处于技术选型阶段，如果可以的话，您的作品也可以成为我的项目的编辑器候选。
但是我想知道您是不是会持续改进您的项目，以及是否可以为我定制一些功能。
谢谢。

**Comment by yutuo** [comment]
> 我想问一下，你自己的MD工具，大概什么时候可以完成？是否为持续改进？
会持续改进，但具体时间上没有一个确定的期限。因为editor.md对Markdown里的HTML处理得不好，所以我现在也是用的自己的写博客。

>但是我想知道您是不是会持续改进您的项目，以及是否可以为我定制一些功能。
我的微信号是：yutuo05，你可以加我
